
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - ecommerce-network

  produto-api:
    build:
      context: .
      dockerfile: ./Ecommerce.Microsservico/Ecommerce.Microsservico.Produto.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    depends_on:
      - "sqlserver"
    networks:
      - ecommerce-network

  usuario-api:
    build:
      context: .
      dockerfile: ./Ecommerce.Microsservico/Ecommerce.Microsservico.Usuario.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
    depends_on:
      - "sqlserver"
    networks:
      - ecommerce-network

  pagamento-api:
    build:
      context: .
      dockerfile: ./Ecommerce.Microsservico/Ecommerce.Microsservico.Pagamento.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:8080"
    depends_on:
      - "sqlserver"
    networks:
      - ecommerce-network

  pedido-api:
    build:
      context: .
      dockerfile: ./Ecommerce.Microsservico/Ecommerce.Microsservico.Pedido.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:8080"
    depends_on:
      - "sqlserver"
    networks:
      - ecommerce-network

  rabbitmq-consumer:
    build:
      context: .
      dockerfile: ./Ecommerce.Microsservico/Consumer/RabbitMqConsumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:8080"
    depends_on:
      - "rabbitmq"
    networks:
      - ecommerce-network
    restart: always

  monolito:
    build:
      context: .
      dockerfile: ./Ecommerce.Monolito/Ecommerce.Monolito/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    depends_on:
      - "sqlserver"
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - ecommerce-network

volumes:
  sqlserver-data:

networks:
  ecommerce-network:
    driver: bridge