// <auto-generated />
using System;
using Ecommerce.Microsservico.Usuario.DbMigrator.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Microsservico.Usuario.DbMigrator.Migrations
{
    [DbContext(typeof(UsuarioDbContext))]
    [Migration("20250315222414_UsuarioDefault")]
    partial class UsuarioDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Commons.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacaoUsuario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "12345678901",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 399, DateTimeKind.Local).AddTicks(3761),
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.silva@example.com",
                            Endereco = "Rua A, 123",
                            Nome = "João Silva",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "23456789012",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9264),
                            DataNascimento = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.souza@example.com",
                            Endereco = "Rua B, 456",
                            Nome = "Maria Souza",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "34567890123",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9302),
                            DataNascimento = new DateTime(1985, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos.pereira@example.com",
                            Endereco = "Rua C, 789",
                            Nome = "Carlos Pereira",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 4,
                            CPF = "45678901234",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9305),
                            DataNascimento = new DateTime(1988, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.costa@example.com",
                            Endereco = "Rua D, 101",
                            Nome = "Ana Costa",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 5,
                            CPF = "56789012345",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9308),
                            DataNascimento = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pedro.almeida@example.com",
                            Endereco = "Rua E, 202",
                            Nome = "Pedro Almeida",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 6,
                            CPF = "67890123456",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9311),
                            DataNascimento = new DateTime(1993, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juliana.santos@example.com",
                            Endereco = "Rua F, 303",
                            Nome = "Juliana Santos",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 7,
                            CPF = "78901234567",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9376),
                            DataNascimento = new DateTime(1987, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rafael.oliveira@example.com",
                            Endereco = "Rua G, 404",
                            Nome = "Rafael Oliveira",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 8,
                            CPF = "89012345678",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9379),
                            DataNascimento = new DateTime(1991, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernanda.lima@example.com",
                            Endereco = "Rua H, 505",
                            Nome = "Fernanda Lima",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 9,
                            CPF = "90123456789",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9382),
                            DataNascimento = new DateTime(1994, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.rocha@example.com",
                            Endereco = "Rua I, 606",
                            Nome = "Lucas Rocha",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 10,
                            CPF = "01234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9385),
                            DataNascimento = new DateTime(1989, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariana.ribeiro@example.com",
                            Endereco = "Rua J, 707",
                            Nome = "Mariana Ribeiro",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 11,
                            CPF = "11234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9387),
                            DataNascimento = new DateTime(1996, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bruno.fernandes@example.com",
                            Endereco = "Rua K, 808",
                            Nome = "Bruno Fernandes",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 12,
                            CPF = "12234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9390),
                            DataNascimento = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia.gomes@example.com",
                            Endereco = "Rua L, 909",
                            Nome = "Patricia Gomes",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 13,
                            CPF = "13234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9392),
                            DataNascimento = new DateTime(1986, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rodrigo.martins@example.com",
                            Endereco = "Rua M, 1010",
                            Nome = "Rodrigo Martins",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 14,
                            CPF = "14234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9394),
                            DataNascimento = new DateTime(1998, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aline.ferreira@example.com",
                            Endereco = "Rua N, 1111",
                            Nome = "Aline Ferreira",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 15,
                            CPF = "15234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9397),
                            DataNascimento = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thiago.barbosa@example.com",
                            Endereco = "Rua O, 1212",
                            Nome = "Thiago Barbosa",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 16,
                            CPF = "16234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9399),
                            DataNascimento = new DateTime(1992, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "camila.araujo@example.com",
                            Endereco = "Rua P, 1313",
                            Nome = "Camila Araujo",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 17,
                            CPF = "17234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9401),
                            DataNascimento = new DateTime(1985, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "felipe.mendes@example.com",
                            Endereco = "Rua Q, 1414",
                            Nome = "Felipe Mendes",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 18,
                            CPF = "18234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9404),
                            DataNascimento = new DateTime(1988, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "renata.carvalho@example.com",
                            Endereco = "Rua R, 1515",
                            Nome = "Renata Carvalho",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 19,
                            CPF = "19234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9406),
                            DataNascimento = new DateTime(1995, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gustavo.lima@example.com",
                            Endereco = "Rua S, 1616",
                            Nome = "Gustavo Lima",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 20,
                            CPF = "20234567890",
                            DataCriacaoUsuario = new DateTime(2025, 3, 15, 19, 24, 14, 400, DateTimeKind.Local).AddTicks(9409),
                            DataNascimento = new DateTime(1993, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabela.souza@example.com",
                            Endereco = "Rua T, 1717",
                            Nome = "Isabela Souza",
                            Senha = "senha123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
